In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME' 'STATUS', 'SPECIAL_CONSIDERATIONS'.
application_df = application_df.drop(columns = ['EIN', 'NAME', 'STATUS', 'SPECIAL_CONSIDERATIONS'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,6692,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,142590,1
...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,0,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,0,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,0,5000,0
34297,T5,Independent,C3000,ProductDev,Association,0,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1M-5M,36500179,0

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE      17
AFFILIATION            6
CLASSIFICATION        71
USE_CASE               5
ORGANIZATION           4
INCOME_AMT             9
ASK_AMT             8747
IS_SUCCESSFUL          2
dtype: int64

In [4]:
# Drop the non-beneficial ID columns, 'ASK_AMT	'.
application_df = application_df.drop(columns = ['ASK_AMT'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,1
...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,0,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,0,0
34296,T3,CompanySponsored,C2000,Preservation,Association,0,0
34297,T5,Independent,C3000,ProductDev,Association,0,1
34298,T3,Independent,C1000,Preservation,Co-operative,1M-5M,0

In [5]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE    17
AFFILIATION          6
CLASSIFICATION      71
USE_CASE             5
ORGANIZATION         4
INCOME_AMT           9
IS_SUCCESSFUL        2
dtype: int64

In [6]:
# Look at APPLICATION_TYPE value counts for binning
type_counts = application_df['APPLICATION_TYPE'].value_counts()
type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(type_counts.iloc[8:].index)
cutoff_value = 528

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other_app_type")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3                27037
T4                 1542
T6                 1216
T5                 1173
T19                1065
T8                  737
T7                  725
T10                 528
Other_app_type      276
Name: APPLICATION_TYPE, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts for binning
classification_types = application_df['CLASSIFICATION'].value_counts()
classification_types

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_types.iloc[5:].index)
cutoff_value_classifications = 1883

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other_classification")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000                   17326
C2000                    6074
C1200                    4837
Other_classification     2261
C3000                    1918
C2100                    1883
Name: CLASSIFICATION, dtype: int64

In [11]:
#convert the categorical data in numeric using get_dummies()
dummies = pd.get_dummies(application_df)
dummies.head()

,IS_SUCCESSFUL,APPLICATION_TYPE_Other_app_type,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1,0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,1,0,0,0,1,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
4,1,0,0,0,1,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0

In [12]:
# Split our preprocessed data into our features and target arrays
y = dummies['IS_SUCCESSFUL'].values
X = dummies.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [14]:
# (FIRST ATTEMPT - ACCURACY 72%)
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features_total = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = input_features_total, activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 320

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 371
Trainable params: 371
Non-trainable params: 0
_________________________________________________________________

In [15]:
# Compile the model (FIRST ATTEMPT)
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [16]:
# Train the model (FIRST ATTEMPT)
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.6208 - accuracy: 0.6807
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5707 - accuracy: 0.7220
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5602 - accuracy: 0.7285
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5552 - accuracy: 0.7309
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5531 - accuracy: 0.7314
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5522 - accuracy: 0.7320
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5513 - accuracy: 0.7331
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5503 - accuracy: 0.7334
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5496 - accuracy: 0.7336
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5490 - accuracy: 0.7325
Epoch 11/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5483 - accuracy: 0.7337
Epoch 12/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7338
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7339
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5479 - accuracy: 0.7334
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5479 - accuracy: 0.7332
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7349
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5477 - accuracy: 0.7338
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5471 - accuracy: 0.7345
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5472 - accuracy: 0.7330
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5471 - accuracy: 0.7338
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5469 - accuracy: 0.7335
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5465 - accuracy: 0.7337
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5467 - accuracy: 0.7353
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5467 - accuracy: 0.7348
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5466 - accuracy: 0.7345
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5463 - accuracy: 0.7346
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5463 - accuracy: 0.7336
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5462 - accuracy: 0.7349
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5464 - accuracy: 0.7346
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5460 - accuracy: 0.7340
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5461 - accuracy: 0.7347
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5459 - accuracy: 0.7348
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5460 - accuracy: 0.7343
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5459 - accuracy: 0.7339
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5460 - accuracy: 0.7340
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5458 - accuracy: 0.7340
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5457 - accuracy: 0.7343
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5459 - accuracy: 0.7352
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5457 - accuracy: 0.7349
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5456 - accuracy: 0.7345
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5455 - accuracy: 0.7339
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5455 - accuracy: 0.7355
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5454 - accuracy: 0.7356
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5452 - accuracy: 0.7354
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5453 - accuracy: 0.7347
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5453 - accuracy: 0.7344
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5453 - accuracy: 0.7349
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5453 - accuracy: 0.7352
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5450 - accuracy: 0.7348
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5451 - accuracy: 0.7348
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5451 - accuracy: 0.7352
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5450 - accuracy: 0.7353
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5450 - accuracy: 0.7358
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7346
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7343
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7346
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7357
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5449 - accuracy: 0.7350
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7353
Epoch 60/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7351
Epoch 61/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7353
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7355
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7354
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7348
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7350
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5446 - accuracy: 0.7343
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7354
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7350
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7349
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7353
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7351
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7352
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7355
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7360
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7360
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5441 - accuracy: 0.7347
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7349
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7361
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5441 - accuracy: 0.7351
Epoch 80/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7360
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7362
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7360
Epoch 83/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7355
Epoch 84/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7353
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7358
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5441 - accuracy: 0.7352
Epoch 87/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7359
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7354
Epoch 89/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7362
Epoch 90/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7363
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7361
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7360
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7358
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5441 - accuracy: 0.7357
Epoch 95/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7359
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7359
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5434 - accuracy: 0.7362
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5441 - accuracy: 0.7362
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5436 - accuracy: 0.7364
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5436 - accuracy: 0.7356

In [17]:
# Evaluate the model using the test data (FIRST ATTEMPT)
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5572 - accuracy: 0.7237 - 531ms/epoch - 2ms/step
Loss: 0.5572069883346558, Accuracy: 0.7237317562103271

In [18]:
# (SECOND ATTEMPT - ACCURACY 72%)
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features_total = len(X_train[0])
hidden_nodes_layer1 = 10
hidden_nodes_layer2 = 10

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = input_features_total, activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 10)                400

 dense_4 (Dense)             (None, 10)                110

 dense_5 (Dense)             (None, 1)                 11

=================================================================
Total params: 521
Trainable params: 521
Non-trainable params: 0
_________________________________________________________________

In [19]:
# Compile the model (SECOND ATTEMPT)
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [20]:
# Train the model (SECOND ATTEMPT)
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 1ms/step - loss: 0.6184 - accuracy: 0.6922
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5711 - accuracy: 0.7270
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5612 - accuracy: 0.7288
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5564 - accuracy: 0.7320
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5534 - accuracy: 0.7331
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5519 - accuracy: 0.7328
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5512 - accuracy: 0.7336
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5502 - accuracy: 0.7336
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5495 - accuracy: 0.7346
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5494 - accuracy: 0.7333
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5487 - accuracy: 0.7343
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5485 - accuracy: 0.7343
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7342
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5481 - accuracy: 0.7343
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5475 - accuracy: 0.7350
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5474 - accuracy: 0.7337
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7347
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5472 - accuracy: 0.7344
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7343
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5469 - accuracy: 0.7345
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5462 - accuracy: 0.7346
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5466 - accuracy: 0.7342
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7348
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5458 - accuracy: 0.7343
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5464 - accuracy: 0.7358
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5458 - accuracy: 0.7356
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5456 - accuracy: 0.7353
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5455 - accuracy: 0.7348
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5450 - accuracy: 0.7355
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5452 - accuracy: 0.7353
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5452 - accuracy: 0.7362
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7352
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5449 - accuracy: 0.7352
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7360
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5449 - accuracy: 0.7352
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7349
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7353
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7360
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7350
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7358
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7357
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7355
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7352
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7357
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5437 - accuracy: 0.7357
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5435 - accuracy: 0.7347
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7363
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7352
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5434 - accuracy: 0.7360
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7357
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7355
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7358
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5435 - accuracy: 0.7362
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5434 - accuracy: 0.7363
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5433 - accuracy: 0.7350
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7360
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5433 - accuracy: 0.7355
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7360
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7352
Epoch 60/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5433 - accuracy: 0.7356
Epoch 61/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7366
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7359
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7351
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7347
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7352
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7355
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5434 - accuracy: 0.7367
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7356
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7361
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7370
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7362
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7359
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7362
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7358
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7360
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7360
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7369
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7364
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7367
Epoch 80/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7367
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7359
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7367
Epoch 83/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7357
Epoch 84/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7356
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7351
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7355
Epoch 87/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7371
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7361
Epoch 89/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7378
Epoch 90/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7364
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7364
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7360
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7362
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7368
Epoch 95/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7353
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7365
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5420 - accuracy: 0.7362
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5420 - accuracy: 0.7362
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7357
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7357

In [21]:
# Evaluate the model using the test data (SECOND ATTEMPT)
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5586 - accuracy: 0.7216 - 993ms/epoch - 4ms/step
Loss: 0.5585845708847046, Accuracy: 0.7216326594352722

In [30]:
# (THIRD ATTEMPT - ACCURACY 72%)
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features_total = len(X_train[0])
hidden_nodes_layer1 = 20
hidden_nodes_layer2 = 20

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = input_features_total, activation = "tanh"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="relu"))

# Check the structure of the model
nn.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_18 (Dense)            (None, 20)                800

 dense_19 (Dense)            (None, 20)                420

 dense_20 (Dense)            (None, 1)                 21

=================================================================
Total params: 1,241
Trainable params: 1,241
Non-trainable params: 0
_________________________________________________________________

In [31]:
# Compile the model (THIRD ATTEMPT)
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [32]:
# Train the model (THIRD ATTEMPT)
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 1ms/step - loss: 1.1039 - accuracy: 0.6670
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5759 - accuracy: 0.7155
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5665 - accuracy: 0.7231
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5638 - accuracy: 0.7265
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5646 - accuracy: 0.7295
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5657 - accuracy: 0.7272
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5591 - accuracy: 0.7312
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5569 - accuracy: 0.7324
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5600 - accuracy: 0.7315
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5533 - accuracy: 0.7318
Epoch 11/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5566 - accuracy: 0.7334
Epoch 12/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5529 - accuracy: 0.7322
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5850 - accuracy: 0.7171
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5541 - accuracy: 0.7336
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5509 - accuracy: 0.7333
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5507 - accuracy: 0.7332
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5528 - accuracy: 0.7316
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5496 - accuracy: 0.7315
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5514 - accuracy: 0.7332
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5494 - accuracy: 0.7332
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5582 - accuracy: 0.7268
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5486 - accuracy: 0.7339
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5603 - accuracy: 0.7287
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5488 - accuracy: 0.7341
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5471 - accuracy: 0.7354
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5490 - accuracy: 0.7346
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5862 - accuracy: 0.7145
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5583 - accuracy: 0.7337
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5504 - accuracy: 0.7343
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5481 - accuracy: 0.7343
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7346
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5466 - accuracy: 0.7345
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5472 - accuracy: 0.7346
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5462 - accuracy: 0.7348
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5479 - accuracy: 0.7351
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5502 - accuracy: 0.7356
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5487 - accuracy: 0.7336
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5505 - accuracy: 0.7356
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5472 - accuracy: 0.7364
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7352
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.7445 - accuracy: 0.7152
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6416 - accuracy: 0.6804
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5649 - accuracy: 0.7300
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5541 - accuracy: 0.7335
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5490 - accuracy: 0.7343
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5464 - accuracy: 0.7366
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5451 - accuracy: 0.7357
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7363
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7361
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5466 - accuracy: 0.7355
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5450 - accuracy: 0.7360
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7349
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5480 - accuracy: 0.7352
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7356
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5466 - accuracy: 0.7358
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5475 - accuracy: 0.7350
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5468 - accuracy: 0.7358
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5451 - accuracy: 0.7360
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5461 - accuracy: 0.7352
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7358
Epoch 61/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5493 - accuracy: 0.7361
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5449 - accuracy: 0.7351
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7360
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5454 - accuracy: 0.7361
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5481 - accuracy: 0.7374
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5460 - accuracy: 0.7369
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7368
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5450 - accuracy: 0.7365
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5600 - accuracy: 0.7315
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5476 - accuracy: 0.7356
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7362
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7372
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7362
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7374
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7367
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5761 - accuracy: 0.7216
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5624 - accuracy: 0.7316
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5505 - accuracy: 0.7334
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5466 - accuracy: 0.7355
Epoch 80/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5451 - accuracy: 0.7361
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7362
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7370
Epoch 83/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7364
Epoch 84/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7363
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7373
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7370
Epoch 87/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7364
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7373
Epoch 89/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7373
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7364
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7365
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5513 - accuracy: 0.7355
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7371
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5420 - accuracy: 0.7367
Epoch 95/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7367
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7369
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7362
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7362
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7362
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7365

In [33]:
# Evaluate the model using the test data (THIRD ATTEMPT)
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5616 - accuracy: 0.7234 - 548ms/epoch - 2ms/step
Loss: 0.5615993142127991, Accuracy: 0.7233819365501404

In [34]:
# Export our model to HDF5 file
filepath = r"C:\Users\John\Deep_Learning_Challenge\deep-learning-challenge\AlphabetSoupCharity_Optimization.h5"
nn.save(filepath, save_format='h5')